name: wowtalent
description: Talent Sharing Multiplatform App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# This section is for packages used in this project
dependencies:

  #Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # Firebase
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  google_sign_in: ^4.5.3

  # Media
  flutter_svg: ^0.18.0
  cached_network_image:
  video_player: ^0.10.8+1
  image_picker: ^0.6.1+11
  transparent_image: ^1.0.0
  flutter_ffmpeg: ^0.2.10
  file_picker: ^1.12.0

  # File System
  filesize: ^1.0.4
  path_provider: ^1.1.0

  # Utilities
  provider: ^4.3.1
  timeago: ^2.0.21

  # Formatting
  characters:
  flutter_facebook_login:
  flutter_spinkit:
  line_icons:
  hexcolor:
  curved_navigation_bar: ^0.3.3
  flutter_staggered_grid_view: ^0.3.2

  # Misc
  flutter_dotenv: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true


  assets:
    - assets/images/