name: wowtalent
description: Talent Sharing Multiplatform App.
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# This section is for packages used in this project
dependencies:

  #Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_auth: ^1.1.1
  firebase_core: ^1.0.4
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4
  firebase_dynamic_links: ^2.0.1
  flutter_facebook_auth: ^3.3.2+2
  google_sign_in: ^5.0.2
  firebase_messaging: ^9.1.2

  # Media
  flutter_svg: ^0.21.0+1
  cached_network_image:
  video_player: ^1.0.0
  image_picker: ^0.7.4
  transparent_image: ^1.0.0
  file_picker: ^3.0.1
  permission_handler: ^6.1.3
  inview_notifier_list: ^1.0.0


  # File System
  filesize: ^1.0.4
  path_provider: ^2.0.1
  video_compress: ^2.1.0
  shared_preferences: ^2.0.5
  flutter_share: ^2.0.0
  dio: ^4.0.0
  screen: ^0.0.5
  fluttertoast: ^8.0.5

  # Utilities
  provider: ^4.3.1
  mailer: ^3.0.4
  timeago: ^3.0.2

  # Formatting
  characters:
  flutter_spinkit:
  line_icons:
  hexcolor:
  curved_navigation_bar: ^0.3.7
  flutter_staggered_grid_view: ^0.4.0
  popup_menu: ^1.0.5
  percent_indicator: ^3.0.1
  animated_background: ^1.0.5
  flutter_advanced_switch: ^0.0.8
  swipe_stack: ^1.0.0
  shimmer: ^2.0.0
  animations: ^2.0.0
  # Misc
  flutter_dotenv: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/videos/
fonts:
  - family: LeagueSpartan
    fonts:
      - asset: assets/fonts/LeagueSpartan-Bold.otf
        weight: 700
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.otf
      - asset: assets/fonts/Montserrat-Bold.otf
        weight: 700