name: wowtalent
description: Talent Sharing Multiplatform App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# This section is for packages used in this project
dependencies:

  #Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  # Firebase
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_dynamic_links: ^0.5.0+11
  flutter_facebook_auth: ^0.2.3
  google_sign_in: ^4.5.3

  # Media
  flutter_svg: ^0.18.0
  cached_network_image:
  video_player: ^0.10.8+1
  image_picker: ^0.6.1+11
  transparent_image: ^1.0.0
  file_picker: ^1.12.0

  # File System
  filesize: ^1.0.4
  path_provider: ^1.1.0
  video_compress: ^2.0.0
  shared_preferences: ^0.5.10
  flutter_share: ^1.0.2+1
  dio: ^3.0.10

  # Utilities
  provider: ^4.3.1
  timeago: ^2.0.21

  # Formatting
  characters:
  flutter_spinkit:
  line_icons:
  hexcolor:
  curved_navigation_bar: ^0.3.3
  flutter_staggered_grid_view: ^0.3.2
  popup_menu: ^1.0.5
  flutter_colored_progress_indicators: ^1.2.0
  animated_background: ^1.0.5

  # Misc
  flutter_dotenv: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/videos/
fonts:
  - family: LeagueSpartan
    fonts:
      - asset: assets/fonts/LeagueSpartan-Bold.otf
        weight: 700
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.otf
      - asset: assets/fonts/Montserrat-Bold.otf
        weight: 700